Simulation and Modeling Lab  
**Course Code:** CSE 413  
**Name:** MD. Safrid Bhuiyan  
**ID:** 0432310005101080  
**Sec:** 7B2; **Batch:** 53   
**Semester:** Spring 2026  
**Assignment No.:** 01  

#📘 Individualized Student Task: Unique Matrix Value Investigation  
🎯 **Objective**  
To analyze how changing matrix values affects matrix properties, using a student-specific matrix.

🧩 Task Rules (Important)  
👉 Each student must use a different matrix generated from their own ID.  

📝 **Task Description**  
**1. Create Your Personal Matrix**
Let:  
● d1 = last digit of your student ID  
● d2 = second last digit of your student ID  
Create the matrix:  

**2. Analyze Matrix A**  
Using NumPy, compute:  
● Shape of A  
● Determinant  
● Rank  
● Eigenvalues  
● Inverse (only if determinant ≠ 0)  

**3. Value Change Experiment**  
Create a new matrix B by changing exactly one value in A:  
● Add +1 to one element of your choice  
● You must clearly state which element you changed  

**4. Re-analyze Matrix B**  
Compute the same properties as in Step 2.  

**5. Comparison & Explanation**  
Answer the following in your own words:  
1. How did the determinant change and why?  
2. Did the rank change? Explain.  
3. How did the eigenvalues respond to the value change?  
4. Is B easier or harder to invert than A? Why?  

# Necessary Libraries

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# 1. Creating Personal Matrix as A

In [2]:
# ID Matrix
d1 = 8
d2 = 0

A = np.array([[d1+2, d2+1],[2*d1, d2+2]])

# Show Matrix
print("Matrix A: \n",A,"\n")


Matrix A: 
 [[10  1]
 [16  2]] 



# 2. Analyze Matrix A

In [3]:
# Shape of A
size_A = A.shape

# Determinant
det_A = np.linalg.det(A)

# Rank
rank_A = np.linalg.matrix_rank(A)

# Eigenvalues
eigenvalA = np.linalg.eigvals(A)

# Inverse (only if determinant ≠ 0)
if np.linalg.det(A) != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Matrix is singular, cannot compute inverse"

# Display results
print("Shape of A:", size_A,"\n")
print("Determinant of A:", det_A,"\n")
print("Rank of A:", rank_A,"\n")
print("Eigenvalues of A:", eigenvalA,"\n")
print("Inverse of A:\n", inv_A,"\n")

Shape of A: (2, 2) 

Determinant of A: 4.0 

Rank of A: 2 

Eigenvalues of A: [11.65685425  0.34314575] 

Inverse of A:
 [[ 0.5  -0.25]
 [-4.    2.5 ]] 



# 3. Value Change Experiment

In [4]:
# New Matrix B
B = np.array([[d1+2, d2+1],[2*d1, d2+3]]) # 4th element as d2+3 instead of d2+2

# Show Matrix
print("Matrix B:\n",B,"\n")

Matrix B:
 [[10  1]
 [16  3]] 



# 4. Re-analyze Matrix B

In [5]:
# Shape of B
size_B = B.shape

# Determinant
det_B = np.linalg.det(B)

# Rank
rank_B = np.linalg.matrix_rank(B)

# Eigenvalues
eigenvalB = np.linalg.eigvals(B)

# Inverse (only if determinant ≠ 0)
if np.linalg.det(B) != 0:
    inv_B = np.linalg.inv(B)
else:
    inv_B = "Matrix is singular, cannot compute inverse"

# Display results
print("Shape of B:", size_B,"\n")
print("Determinant of B:", det_B,"\n")
print("Rank of B:", rank_B,"\n")
print("Eigenvalues of B:", eigenvalB,"\n")
print("Inverse of B:\n", inv_B,"\n")

Shape of B: (2, 2) 

Determinant of B: 13.999999999999996 

Rank of B: 2 

Eigenvalues of B: [11.81507291  1.18492709] 

Inverse of B:
 [[ 0.21428571 -0.07142857]
 [-1.14285714  0.71428571]] 



# 5. Comparison & Explanation

**Q1. How did the determinant change and why?**  
A: For a 2×2 matrix, determinant = ad − bc.  
  
      Det(A) = (8×11) − (10×12) = 88 − 120 = −32  
      Det(B) = (8×12) − (10×12) = 96 − 120 = −24  

The determinant increased from −32 to −24.  
It changed because the determinant depends directly on the values of the matrix elements.When I increased one element (bottom-right) by 1, it increased the product ad, which changed the final subtraction result. Even a small change in one element can significantly affect the determinant.  
  
  
**Q2. Did the rank change? Explain.**  
A: No, the rank did not change.  

Both matrices still have non-zero determinants. For a 2×2 matrix, if the determinant is not zero, the rank is 2 (full rank). Since both −32 and −24 are non-zero, both matrices remain full rank.  

So the rank stays 2.  
  
  
**Q3. How did the eigenvalues respond to the value change?**  
A: The eigenvalues changed slightly.  

Eigenvalues depend on both the trace (sum of diagonal elements) and the determinant. Since we increased one diagonal element, the trace increased, and the determinant also changed. Because eigenvalues are calculated from these values, they adjusted accordingly.  

So the eigenvalues did not remain the same — they shifted due to the modification in the matrix.  


**Q4. Is B easier or harder to invert than A? Why?**  
A: Both matrices are invertible because their determinants are non-zero.  

But, B is slightly harder to invert than A.  

This is because B has a smaller absolute determinant (|−24|) compared to A (|−32|). A smaller determinant means the matrix is closer to singular (zero determinant), which makes the inverse less stable.  
  
So, A is slightly easier (more stable) to invert than B.

# Hence, All the given tasks of Assignment 2 are Completed.